In [17]:
import pandas as pd

data = {
    "name": ["Ali", "Omar", "Sara"],
    "age": [20, 25, 22]
}

df = pd.DataFrame(data, index=["a", "b", "c"])
df

   name  age
a   Ali   20
b  Omar   25
c  Sara   22

In [18]:
df.loc["a","age"]

np.int64(20)

In [19]:
df.loc["a":"c",["name","age"]]

   name  age
a   Ali   20
b  Omar   25
c  Sara   22

In [15]:
df.iloc[0:2,[0,1]]

   name  age
a   Ali   20
b  Omar   25

In [22]:
data_trail=df[df["age"]>21]
data_trail.head()

   name  age
b  Omar   25
c  Sara   22

In [1]:
print('salem')

salem

In [2]:
import pandas as pd

In [26]:
table= pd.DataFrame(
    {
        "name":["salem","ziad","mariam","shimaa"],
        "age":[17,23,30,60],
        "sex":["male","male","female","female"],
        "salary":[1000.5,5000,10000,3000]
    }
)

table

     name  age     sex   salary
0   salem   17    male   1000.5
1    ziad   23    male   5000.0
2  mariam   30  female  10000.0
3  shimaa   60  female   3000.0

In [22]:
table["salary"].max()

np.int64(10000)

In [24]:
table.describe()

             age        salary
count   4.000000      4.000000
mean   32.500000   4750.000000
std    19.087518   3862.210075
min    17.000000   1000.000000
25%    21.500000   2500.000000
50%    26.500000   4000.000000
75%    37.500000   6250.000000
max    60.000000  10000.000000

In [27]:
table.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   sex     4 non-null      str
 3   salary  4 non-null      float64
dtypes: float64(1), int64(1), str(2)
memory usage: 260.0 bytes

In [33]:
data=pd.read_csv("employee_salary.csv")
data.tail(10)

,Employee_ID,Age,Years_Experience,Hours_Per_Week,Performance_Score,Department,Job_Level,Education,Salary
20,E021,50,25,44,94,Management,Director,MBA,175000
21,E022,35,9,40,82,Finance,Senior,Bachelor,98000
22,E023,28,3,37,70,IT,Junior,Bachelor,55000
23,E024,42,17,41,87,HR,Senior,Master,78000
24,E025,46,21,43,90,Engineering,Lead,Master,140000
25,E026,31,5,39,75,Marketing,Mid,Bachelor,56000
26,E027,37,12,40,83,Finance,Senior,Bachelor,102000
27,E028,24,1,35,58,IT,Junior,High School,36000
28,E029,49,24,44,92,Engineering,Director,PhD,160000
29,E030,33,7,40,79,HR,Mid,Bachelor,63000

In [31]:
data.describe()

,Age,Years_Experience,Hours_Per_Week,Performance_Score,Salary
count,30.000000,30.000000,30.000000,30.000000,30.000000
mean,37.033333,11.966667,40.233333,81.566667,98033.333333
std,8.731565,8.656205,2.836746,10.630741,50105.050563
min,24.000000,1.000000,35.000000,58.000000,36000.000000
25%,30.250000,5.000000,38.250000,74.250000,56500.000000
50%,35.500000,10.000000,40.000000,83.500000,90000.000000
75%,43.750000,18.750000,42.000000,90.000000,138750.000000
max,55.000000,30.000000,46.000000,97.000000,220000.000000

In [32]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        30 non-null     str
 1   Age                30 non-null     int64
 2   Years_Experience   30 non-null     int64
 3   Hours_Per_Week     30 non-null     int64
 4   Performance_Score  30 non-null     int64
 5   Department         30 non-null     str
 6   Job_Level          30 non-null     str
 7   Education          30 non-null     str
 8   Salary             30 non-null     int64
dtypes: int64(5), str(4)
memory usage: 2.2 KB

In [35]:
data["Age"]

0     34
1     28
2     45
3     31
4     52
5     26
6     39
7     33
8     41
9     29
10    48
11    36
12    27
13    44
14    55
15    32
16    38
17    25
18    43
19    30
20    50
21    35
22    28
23    42
24    46
25    31
26    37
27    24
28    49
29    33
Name: Age, dtype: int64

In [36]:
data["Age"].min()

np.int64(24)

In [37]:
data["Age"].max()

np.int64(55)

In [38]:
data["Salary"].sum()

np.int64(2941000)

In [40]:
data.shape

(30, 9)

In [46]:
data[(data["Age"] < 35) & (data["Salary"]>90000)]

,Employee_ID,Age,Years_Experience,Hours_Per_Week,Performance_Score,Department,Job_Level,Education,Salary
0,E001,34,8,40,87,Engineering,Senior,Bachelor,95000

In [49]:
data.loc[data["Department"]=="Engineering"]

,Employee_ID,Age,Years_Experience,Hours_Per_Week,Performance_Score,Department,Job_Level,Education,Salary
0,E001,34,8,40,87,Engineering,Senior,Bachelor,95000
2,E003,45,20,42,92,Engineering,Lead,Master,135000
8,E009,41,16,43,90,Engineering,Lead,PhD,145000
13,E014,44,19,41,89,Engineering,Senior,Master,118000
18,E019,43,18,42,91,Engineering,Lead,PhD,150000
24,E025,46,21,43,90,Engineering,Lead,Master,140000
28,E029,49,24,44,92,Engineering,Director,PhD,160000

In [52]:
data.iloc[0:9,[0,1]]

  Employee_ID  Age
0        E001   34
1        E002   28
2        E003   45
3        E004   31
4        E005   52
5        E006   26
6        E007   39
7        E008   33
8        E009   41

In [ ]:
pip install seaborn

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
data=pd.read_csv("DATA.csv")
data.head()